### ISSUE TITLE
MM maps problem

### ISSUE THREAD

**Issue by attaurrahman1** [sheezzmee/shizoval#8]
After updating this script the hack is not working in MM maps.

**Comment by T0HBA** [comment]
use this hack for MM maps https://github.com/T0HBA/TOHBA/raw/main/release/TOHBA.user.js

**Comment by T0HBA** [comment]
Repository owner deleted a comment from T0HBA

try my hack for MM maps:
https://github.com/T0HBA/TOHBA/raw/main/release/TOHBA.user.js
